services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - vaultwarden-data:/data
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - DOMAIN=https://vault.${DOMAIN}
      - SIGNUPS_ALLOWED=true
      - SHOW_PASSWORD_HINT=false
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/alive || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      traefik.enable: true
      traefik.http.routers.vaultwarden.entrypoints: https
      traefik.http.routers.vaultwarden.rule: Host(`vault.${DOMAIN}`)
      traefik.http.services.vaultwarden.loadbalancer.server.port: 80

networks:
  proxy:
    external: true

volumes:
  vaultwarden-data:
