services:
  trala:
    image: ghcr.io/dannybouwers/trala:latest  # Primary source
    container_name: trala
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TRAEFIK_API_HOST=https://traefik.${DOMAIN}
      - LOG_LEVEL=debug
    volumes:
      - /home/docker/compose/trala/configuration.yml:/config/configuration.yml
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      traefik.enable: true
      traefik.http.routers.home.entrypoints: https
      traefik.http.routers.home.rule: Host(`home.${DOMAIN}`)
      traefik.http.services.home.loadbalancer.server.port: 8080

networks:
  proxy:
    external: true
volumes:
  config:
